# Generated by Django 4.0.4 on 2023-04-16 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='profile-image-placeholder.png', upload_to='profile-image/%h/%Y/')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('deposit_before', models.BooleanField(default=False)),
                ('refer_clicks', models.IntegerField(blank=True, default=0, null=True)),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('refers', models.ManyToManyField(blank=True, related_name='refers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_address', models.TextField(blank=True, null=True)),
                ('bonus', models.CharField(blank=True, default='0', max_length=10)),
                ('balance', models.CharField(blank=True, default='00.00', max_length=100)),
                ('pin', models.CharField(blank=True, max_length=6)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('credit', 'credit'), ('processing', 'processing'), ('confirming', 'confirming'), ('error', 'error'), ('failed', 'failed')], max_length=15)),
                ('msg', models.TextField(blank=True)),
                ('transactionId', models.CharField(blank=True, max_length=17)),
                ('hash_id', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.wallet')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_address', models.TextField(unique=True)),
                ('returns', models.CharField(blank=True, max_length=100)),
                ('bad', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AdminTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('btc_address', models.TextField()),
                ('msg', models.TextField(blank=True)),
                ('transactionId', models.CharField(blank=True, max_length=17)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.wallet')),
            ],
        ),
    ]
