# Generated by Django 5.0 on 2023-12-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_email_remove_wallet_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
