# Generated by Django 4.0.4 on 2022-05-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_admintransaction_btc_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='btc_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
