# Generated by Django 5.0 on 2024-04-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount_invested',
            field=models.CharField(blank=True, default='00.00', max_length=100),
        ),
    ]
