# Generated by Django 5.0 on 2024-09-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_wallet_amount_invested'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
